"""LoRA Lab window — deploy trained kohya checkpoints as live LoRA slugs.

Flow (all server-side state, autogenerated — no git-tracked config):

  browse trained LoRAs (kohya datasets → runs, scanned server-side)
    → pick a checkpoint (step-ordered)
    → pick a caption subset (training captions, or the curated
      preview shortlist when one exists)
    → Deploy: the server copies the checkpoint into its deployed-LoRAs
      dir, writes the caption subset as the slug's prompt file, and
      refreshes its disk-derived slug registry.

The deploy/pair responses carry the updated slug + preset lists; the
window re-emits them as ``registry_updated`` so main.py can repopulate
the LoRA hot-swap dropdowns in place — the new LoRA is selectable in the
blending dropdown immediately, no reconnect / restart.

A second section pairs two deployed slugs into a curation-index preset
(requires equal prompt counts — paired prompt travel needs A[k]↔B[k]).

Server endpoints (web/server_realtime.py on sdxl-travel-ablation):
  GET  /api/installations/plantoid16/lora_lab          catalog + deployed
  POST /api/installations/plantoid16/lora_lab/deploy   {dataset, run_id,
                                                        checkpoint,
                                                        captions, slug}
  POST /api/installations/plantoid16/lora_lab/pair     {slug_a, slug_b}

HTTP runs in daemon worker threads; results come back via Qt signals
(queued to the GUI thread automatically).
"""

import re
import threading

import requests
from PySide6.QtCore import Qt, Signal
from PySide6.QtGui import QFont, QFontMetrics, QPixmap
from PySide6.QtWidgets import (QCheckBox, QComboBox, QGridLayout, QGroupBox,
                               QHBoxLayout, QLabel, QLineEdit, QPushButton,
                               QScrollArea, QSplitter, QTreeWidget,
                               QTreeWidgetItem, QVBoxLayout, QWidget)

_STEP_RE = re.compile(r"[-_](?:step)?0*(\d+)\.safetensors$")

_THUMB = 200          # thumbnail edge in the caption grid
_CELL_MARGIN = 6      # card inner margin
_TEXT_LINES = 4       # caption lines on image cards (elided beyond)
_TEXT_PT = 10         # caption font size
_GRID_SPACING = 8     # gap between cards
_FALLBACK_COLS = 3    # used before the viewport has a real width

_STYLE = """
QWidget { background: #11141b; color: #93a3bd; }
QGroupBox { border: 1px solid #1c2130; border-radius: 4px;
            margin-top: 10px; padding-top: 12px; }
QGroupBox::title { subcontrol-origin: margin; left: 8px; color: #7fd4ff; }
QTreeWidget, QListWidget { background: #0c0f15; border: 1px solid #1c2130; }
QLineEdit, QComboBox { background: #0c0f15; border: 1px solid #1c2130;
                       padding: 3px; }
QPushButton { background: #1c2130; border: 1px solid #2a3145;
              padding: 5px 12px; border-radius: 3px; }
QPushButton:hover { background: #2a3145; }
QPushButton:disabled { color: #4a5468; }
"""


def _slug_from_checkpoint(checkpoint: str) -> str:
    """Mirror of the server's suggestion: fire_XL-step00000700 → fire-xl."""
    stem = checkpoint
    if stem.endswith(".safetensors"):
        stem = _STEP_RE.sub("", stem)
        stem = stem[:-len(".safetensors")] if stem.endswith(".safetensors") else stem
    slug = stem.lower().replace("_", "-").strip("-")
    slug = re.sub(r"[^a-z0-9-]+", "-", slug)
    slug = re.sub(r"-{2,}", "-", slug).strip("-")
    return slug or "lora"


def _wrap_elide(text: str, fm: QFontMetrics, width: int, max_lines: int) -> str:
    """Greedy word-wrap ``text`` to ``max_lines`` of ``width`` px, eliding
    the last line with … when the caption overflows the card."""
    words = text.split()
    lines: list[str] = []
    i = 0
    while i < len(words) and len(lines) < max_lines:
        line = words[i]
        i += 1
        while i < len(words):
            cand = line + " " + words[i]
            if fm.horizontalAdvance(cand) <= width:
                line = cand
                i += 1
            else:
                break
        lines.append(line)
    if i < len(words) and lines:  # overflow → elide the last visible line
        rest = lines[-1] + " " + " ".join(words[i:])
        lines[-1] = fm.elidedText(rest, Qt.ElideRight, width)
    return "\n".join(lines)


_CHECK_STYLE = """
QCheckBox { background: rgba(12, 15, 21, 190); border: 1px solid #2a3145;
            border-radius: 3px; padding: 2px; spacing: 0px; }
QCheckBox::indicator { width: 15px; height: 15px; border-radius: 2px;
                       border: 1px solid #93a3bd; background: #0c0f15; }
QCheckBox::indicator:checked { background: #7fd4ff; border-color: #7fd4ff; }
"""


class _CaptionCell(QWidget):
    """One image+caption card in the selection grid (kohya-viz style).

    Fixed-size cards: thumbnail with an inclusion checkbox embedded
    top-left, caption below (larger font, word-wrapped, elided past
    ``_TEXT_LINES``; full text in the tooltip). Click anywhere on the
    card to toggle. Unchecked by default. Shortlist entries have no
    training image — the checkbox sits in a header row instead and the
    caption gets the freed lines.
    """

    toggled = Signal()

    def __init__(self, caption: str, image_key, parent=None):
        super().__init__(parent)
        self.caption = caption
        self.image_key = image_key   # run-relative image path, or None
        self.setObjectName("capCell")
        self.setAttribute(Qt.WA_StyledBackground, True)
        self.setCursor(Qt.PointingHandCursor)
        self.setToolTip(caption)
        self.setStyleSheet(
            "QWidget#capCell { background: #0c0f15; "
            "border: 1px solid #1c2130; border-radius: 4px; }")

        v = QVBoxLayout(self)
        v.setContentsMargins(_CELL_MARGIN, _CELL_MARGIN,
                             _CELL_MARGIN, _CELL_MARGIN)
        v.setSpacing(4)

        # Inclusion checkbox — none selected by default.
        self.check = QCheckBox()
        self.check.setChecked(False)
        self.check.setStyleSheet(_CHECK_STYLE)
        self.check.setCursor(Qt.PointingHandCursor)
        self.check.toggled.connect(lambda _v: self.toggled.emit())

        # Prompt-file position chip ("order in the txt") — shown next to
        # the checkbox for selected cards; see LoraLabView's header update
        # for the numbering. Locates offending prompts by line number.
        self.order_label = QLabel("")
        self.order_label.setStyleSheet(
            "background: rgba(12, 15, 21, 190); border: 1px solid #2a3145;"
            "border-radius: 3px; padding: 1px 5px;"
            "color: #7fd4ff; font-weight: bold;")
        self.order_label.setVisible(False)

        self.thumb = QLabel("…")
        self.thumb.setFixedSize(_THUMB, _THUMB)
        self.thumb.setAlignment(Qt.AlignCenter)
        self.thumb.setStyleSheet(
            "background: #0c0f15; border: 1px solid #1c2130; color: #4a5468;")

        f = QFont()
        f.setPointSize(_TEXT_PT)
        fm = QFontMetrics(f)
        text_w = _THUMB - 4
        text_h = fm.lineSpacing() * _TEXT_LINES + 4

        if image_key is not None:
            v.addWidget(self.thumb, 0, Qt.AlignHCenter)
            # Embed checkbox + order chip in the preview's top-left corner.
            self._overlay = QWidget(self.thumb)
            oh = QHBoxLayout(self._overlay)
            oh.setContentsMargins(0, 0, 0, 0)
            oh.setSpacing(4)
            oh.addWidget(self.check)
            oh.addWidget(self.order_label)
            self._overlay.move(6, 6)
            self._overlay.raise_()
            n_lines = _TEXT_LINES
        else:
            self._overlay = None
            self.thumb.setVisible(False)
            head = QHBoxLayout()
            head.addWidget(self.check)
            head.addWidget(self.order_label)
            head.addStretch(1)
            v.addLayout(head)
            # Text-only card: caption inherits the thumbnail's vertical
            # budget (same fixed card height as its image siblings).
            spare = _THUMB + 4 - (self.check.sizeHint().height() + 4)
            n_lines = _TEXT_LINES + max(0, spare // fm.lineSpacing())

        self.text = QLabel(_wrap_elide(caption, fm, text_w, n_lines))
        self.text.setFont(f)
        self.text.setFixedWidth(_THUMB)
        self.text.setAlignment(Qt.AlignTop | Qt.AlignLeft)
        self.text.setStyleSheet("color: #93a3bd; border: none;")
        v.addWidget(self.text)
        v.addStretch(1)

        # Generous uniform card size — grids stay perfectly aligned and
        # long captions elide instead of stretching their row.
        self.setFixedSize(
            _THUMB + 2 * _CELL_MARGIN + 2,
            _THUMB + text_h + 2 * _CELL_MARGIN + 4 + 2,
        )

    def set_thumbnail(self, pix: QPixmap):
        self.thumb.setText("")
        self.thumb.setPixmap(pix.scaled(
            _THUMB, _THUMB, Qt.KeepAspectRatio, Qt.SmoothTransformation))
        if self._overlay is not None:
            self._overlay.raise_()

    def set_order(self, n):
        """Show/clear the card's 1-based line number in the prompt file."""
        if n is None:
            self.order_label.setVisible(False)
        else:
            self.order_label.setText(str(n))
            self.order_label.setVisible(True)
            if self._overlay is not None:
                self._overlay.adjustSize()
                self._overlay.raise_()

    def is_checked(self) -> bool:
        return self.check.isChecked()

    def set_checked(self, val: bool):
        self.check.setChecked(bool(val))

    def mousePressEvent(self, _event):
        self.check.toggle()


class LoraLabView(QWidget):
    """Deploy-pipeline window; see module docstring."""

    # (slugs, presets) — fresh registry after a deploy / pair-create.
    registry_updated = Signal(list, dict)

    # Internal: worker-thread → GUI-thread result delivery.
    _catalog_done = Signal(object, str)   # (payload | None, error)
    _deploy_done = Signal(object, str)
    _pair_done = Signal(object, str)
    _thumb_done = Signal(int, int, bytes)  # (generation, cell idx, jpeg)

    def __init__(self, base_url_provider, parent=None):
        super().__init__(parent)
        self._base_url = base_url_provider
        self._catalog = None          # last GET /lora_lab payload
        self._current_run = None      # (dataset_name, run_dict)
        self._slug_edited = False     # user typed a custom slug
        self._busy = False
        self._cells = []              # _CaptionCell widgets, grid order
        self._thumb_gen = 0           # invalidates in-flight thumb loads

        self.setWindowTitle("LoRA Lab")
        self.resize(1180, 700)
        self.setStyleSheet(_STYLE)
        self._build_ui()

        self._catalog_done.connect(self._on_catalog_done)
        self._deploy_done.connect(self._on_deploy_done)
        self._pair_done.connect(self._on_pair_done)
        self._thumb_done.connect(self._on_thumb)

    # -- UI ------------------------------------------------------------------

    def _build_ui(self):
        root = QVBoxLayout(self)

        top = QHBoxLayout()
        self.refresh_button = QPushButton("Refresh Catalog")
        self.refresh_button.clicked.connect(self.refresh_catalog)
        top.addWidget(self.refresh_button)
        self.status_label = QLabel("")
        self.status_label.setWordWrap(True)
        top.addWidget(self.status_label, 1)
        root.addLayout(top)

        split = QSplitter(Qt.Horizontal)
        self._split = split
        # Re-flow the caption grid when the splitter changes the space
        # available to the right panel.
        split.splitterMoved.connect(lambda *_: self._relayout_grid())
        root.addWidget(split, 1)

        # Left: trained LoRAs (datasets → runs).
        left = QWidget()
        ll = QVBoxLayout(left)
        ll.setContentsMargins(0, 0, 0, 0)
        ll.addWidget(QLabel("Trained LoRAs (kohya runs)"))
        self.tree = QTreeWidget()
        self.tree.setHeaderHidden(True)
        self.tree.itemSelectionChanged.connect(self._on_run_selected)
        ll.addWidget(self.tree, 1)
        split.addWidget(left)

        # Right: deploy panel + pair panel.
        right = QWidget()
        rl = QVBoxLayout(right)
        rl.setContentsMargins(0, 0, 0, 0)

        deploy_box = QGroupBox("Deploy checkpoint + captions as a live LoRA")
        dl = QVBoxLayout(deploy_box)

        row = QHBoxLayout()
        row.addWidget(QLabel("Checkpoint"))
        self.ckpt_combo = QComboBox()
        self.ckpt_combo.currentTextChanged.connect(self._on_ckpt_changed)
        row.addWidget(self.ckpt_combo, 1)
        dl.addLayout(row)

        row = QHBoxLayout()
        row.addWidget(QLabel("Slug"))
        self.slug_edit = QLineEdit()
        self.slug_edit.setPlaceholderText("e.g. fire-xl")
        self.slug_edit.textEdited.connect(self._on_slug_edited)
        row.addWidget(self.slug_edit, 1)
        dl.addLayout(row)

        self.trigger_label = QLabel("")
        f = QFont(); f.setItalic(True)
        self.trigger_label.setFont(f)
        dl.addWidget(self.trigger_label)

        cap_row = QHBoxLayout()
        self.captions_header = QLabel("Captions")
        cap_row.addWidget(self.captions_header, 1)
        self.src_combo = QComboBox()
        self.src_combo.addItem("training captions")
        self.src_combo.currentIndexChanged.connect(self._populate_captions)
        cap_row.addWidget(self.src_combo)
        for text, slot in (("All", self._check_all),
                           ("None", self._check_none)):
            b = QPushButton(text)
            # No fixed width — let the style's padding size the button
            # (a 52 px fixed width clipped "None").
            b.clicked.connect(slot)
            cap_row.addWidget(b)
        dl.addLayout(cap_row)

        # Image + caption card grid (kohya-viz style): visually pick which
        # captions ship as prompts. Thumbs stream in asynchronously; the
        # column count adapts to the available width (see _relayout_grid).
        self.captions_scroll = QScrollArea()
        self.captions_scroll.setWidgetResizable(True)
        self._grid_host = QWidget()
        self.captions_grid = QGridLayout(self._grid_host)
        self.captions_grid.setSpacing(_GRID_SPACING)
        self.captions_scroll.setWidget(self._grid_host)
        dl.addWidget(self.captions_scroll, 1)

        self.deploy_button = QPushButton("Deploy LoRA")
        self.deploy_button.clicked.connect(self._deploy)
        self.deploy_button.setEnabled(False)
        dl.addWidget(self.deploy_button)
        rl.addWidget(deploy_box, 1)

        pair_box = QGroupBox("Create pair (curation preset)")
        pl = QHBoxLayout(pair_box)
        self.pair_a = QComboBox()
        self.pair_b = QComboBox()
        self.pair_a.currentTextChanged.connect(self._validate_pair)
        self.pair_b.currentTextChanged.connect(self._validate_pair)
        pl.addWidget(QLabel("A"))
        pl.addWidget(self.pair_a, 1)
        pl.addWidget(QLabel("B"))
        pl.addWidget(self.pair_b, 1)
        self.pair_info = QLabel("")
        pl.addWidget(self.pair_info)
        self.pair_button = QPushButton("Create Pair")
        self.pair_button.clicked.connect(self._create_pair)
        self.pair_button.setEnabled(False)
        pl.addWidget(self.pair_button)
        rl.addWidget(pair_box)

        split.addWidget(right)
        split.setSizes([320, 840])

    # -- HTTP plumbing -------------------------------------------------------

    def _api(self, path: str) -> str:
        return f"{self._base_url()}/api/installations/plantoid16/{path}"

    def _get_async(self, path, done_signal):
        url = self._api(path)

        def work():
            try:
                r = requests.get(url, timeout=30)
                r.raise_for_status()
                done_signal.emit(r.json(), "")
            except Exception as e:
                done_signal.emit(None, str(e))

        threading.Thread(target=work, daemon=True).start()

    def _post_async(self, path, payload, done_signal):
        url = self._api(path)

        def work():
            try:
                r = requests.post(url, json=payload, timeout=120)
                if r.status_code >= 400:
                    # Surface FastAPI's {"detail": ...} instead of a bare
                    # status code.
                    try:
                        detail = r.json().get("detail", r.text)
                    except Exception:
                        detail = r.text
                    done_signal.emit(None, f"{r.status_code}: {detail}")
                    return
                done_signal.emit(r.json(), "")
            except Exception as e:
                done_signal.emit(None, str(e))

        threading.Thread(target=work, daemon=True).start()

    # -- catalog -------------------------------------------------------------

    def refresh_catalog(self):
        if self._busy:
            return
        self.status_label.setText("Loading catalog…")
        self.refresh_button.setEnabled(False)
        self._get_async("lora_lab", self._catalog_done)

    def _on_catalog_done(self, payload, error):
        self.refresh_button.setEnabled(True)
        if error:
            self.status_label.setText(f"Catalog fetch failed: {error}")
            return
        self._catalog = payload
        cat = payload.get("catalog", {})
        n_ds = len(cat.get("datasets", []))
        n_deployed = len(payload.get("deployed", {}))
        self.status_label.setText(
            f"{n_ds} trained dataset(s) under {cat.get('kohya_root', '?')} · "
            f"{n_deployed} deployed slug(s)"
        )
        self._populate_tree()
        self._populate_pair_combos()

    def _populate_tree(self):
        self.tree.clear()
        cat = (self._catalog or {}).get("catalog", {})
        for ds in cat.get("datasets", []):
            top = QTreeWidgetItem([ds["name"]])
            top.setFlags(top.flags() & ~Qt.ItemIsSelectable)
            for run in ds.get("runs", []):
                n_ck = len(run.get("checkpoints", []))
                n_cap = len(run.get("captions", []))
                label = f"{run['run_id']} · {n_ck} ckpt · {n_cap} captions"
                if run.get("shortlist"):
                    label += f" · shortlist({len(run['shortlist'])})"
                child = QTreeWidgetItem([label])
                child.setData(0, Qt.UserRole, (ds["name"], run))
                top.addChild(child)
            self.tree.addTopLevelItem(top)
        self.tree.expandAll()

    # -- run / checkpoint / captions selection -------------------------------

    def _on_run_selected(self):
        items = self.tree.selectedItems()
        data = items[0].data(0, Qt.UserRole) if items else None
        if not data:
            return
        ds_name, run = data
        self._current_run = (ds_name, run)
        self._slug_edited = False

        self.ckpt_combo.blockSignals(True)
        self.ckpt_combo.clear()
        for ck in run.get("checkpoints", []):
            step = ck.get("step")
            label = ck["file"] if step is None else f"{ck['file']}  (step {step})"
            self.ckpt_combo.addItem(label, ck["file"])
        # Default to the LAST (highest-step) checkpoint.
        if self.ckpt_combo.count():
            self.ckpt_combo.setCurrentIndex(self.ckpt_combo.count() - 1)
        self.ckpt_combo.blockSignals(False)

        # But prefer the slug's currently-DEPLOYED checkpoint when one
        # exists — reopening a deployed LoRA reflects what's live (same
        # spirit as the caption pre-selection).
        cand = self.ckpt_combo.currentData()
        if cand:
            dep = self._deployed().get(_slug_from_checkpoint(cand)) or {}
            dep_ck = dep.get("checkpoint")
            if dep_ck:
                idx = self.ckpt_combo.findData(dep_ck)
                if idx >= 0:
                    self.ckpt_combo.setCurrentIndex(idx)

        trig = run.get("trigger")
        self.trigger_label.setText(f"trigger: {trig}" if trig else "")

        self.src_combo.blockSignals(True)
        self.src_combo.clear()
        self.src_combo.addItem("training captions")
        if run.get("shortlist"):
            self.src_combo.addItem("curated shortlist")
        self.src_combo.blockSignals(False)

        self._suggest_slug()
        self._populate_captions()
        self.deploy_button.setEnabled(True)

    def _on_ckpt_changed(self, _text):
        self._suggest_slug()

    def _on_slug_edited(self, _text):
        self._slug_edited = True

    def _suggest_slug(self):
        if self._slug_edited:
            return
        ck = self.ckpt_combo.currentData()
        if ck:
            self.slug_edit.setText(_slug_from_checkpoint(ck))

    def _caption_pool_items(self):
        """Current caption source as [{"caption", "image"}, ...].

        Training captions carry their paired image (thumb-able); shortlist
        entries are curated prompt text with no image. Falls back to the
        plain ``captions`` list when talking to a server without
        ``caption_items``.
        """
        if not self._current_run:
            return []
        _ds, run = self._current_run
        if self.src_combo.currentText() == "curated shortlist":
            return [{"caption": s, "image": None}
                    for s in (run.get("shortlist") or [])]
        items = run.get("caption_items")
        if items:
            return items
        return [{"caption": c, "image": None}
                for c in (run.get("captions") or [])]

    def _populate_captions(self):
        # Invalidate in-flight thumbnail loads for the previous grid.
        self._thumb_gen += 1
        while self.captions_grid.count():
            item = self.captions_grid.takeAt(0)
            w = item.widget()
            if w is not None:
                w.deleteLater()
        self._cells = []

        pool = self._caption_pool_items()
        for it in pool:
            cell = _CaptionCell(it["caption"], it.get("image"))
            cell.toggled.connect(self._update_captions_header)
            self._cells.append(cell)

        # Pre-select the slug's EXISTING deployed caption set (if any) so
        # a redeploy starts from what's live — unselect the offenders,
        # add others, redeploy.
        n_pre = self._preselect_deployed()
        self._relayout_grid(force=True)
        self._update_captions_header()
        if n_pre:
            self.status_label.setText(
                f"Pre-selected {n_pre} caption(s) from the deployed "
                f"'{self.slug_edit.text().strip()}' prompt file")

        if self._current_run and any(it.get("image") for it in pool):
            ds_name, run = self._current_run
            self._start_thumb_loader(ds_name, run["run_id"], pool)

    def _preselect_deployed(self) -> int:
        """Check the cards whose caption is in the current slug's deployed
        prompt file. Returns how many were pre-selected (0 = fresh slug)."""
        slug = self.slug_edit.text().strip()
        lines = (self._deployed().get(slug) or {}).get("prompt_lines") or []
        if not lines:
            return 0
        existing = {" ".join(ln.split()) for ln in lines}
        n = 0
        for cell in self._cells:
            if " ".join(cell.caption.split()) in existing:
                cell.set_checked(True)
                n += 1
        return n

    def _grid_col_count(self) -> int:
        """Columns that fit the scroll viewport at the fixed card width."""
        vp = self.captions_scroll.viewport().width()
        if vp <= 0 or not self._cells:
            return _FALLBACK_COLS
        cell_w = self._cells[0].width()
        return max(1, (vp - _GRID_SPACING) // (cell_w + _GRID_SPACING))

    def _relayout_grid(self, force: bool = False):
        """(Re)place the cards at as many columns as fit the width."""
        if not self._cells:
            return
        cols = self._grid_col_count()
        if not force and cols == getattr(self, "_grid_cols", None):
            return
        # Clear stale stretch factors from the previous geometry, then
        # detach every item (widgets survive; they're re-added below).
        old_col = getattr(self, "_stretch_col", None)
        old_row = getattr(self, "_stretch_row", None)
        if old_col is not None:
            self.captions_grid.setColumnStretch(old_col, 0)
        if old_row is not None:
            self.captions_grid.setRowStretch(old_row, 0)
        while self.captions_grid.count():
            self.captions_grid.takeAt(0)
        for i, cell in enumerate(self._cells):
            self.captions_grid.addWidget(cell, i // cols, i % cols,
                                         Qt.AlignTop | Qt.AlignLeft)
        rows = (len(self._cells) + cols - 1) // cols
        self.captions_grid.setColumnStretch(cols, 1)
        self.captions_grid.setRowStretch(rows, 1)
        self._grid_cols = cols
        self._stretch_col = cols
        self._stretch_row = rows

    def resizeEvent(self, event):
        super().resizeEvent(event)
        self._relayout_grid()

    def _start_thumb_loader(self, dataset, run_id, items):
        """Stream thumbnails into the grid from one daemon worker."""
        gen = self._thumb_gen
        url = self._api("lora_lab/thumb")

        def work():
            for idx, it in enumerate(items):
                if gen != self._thumb_gen:
                    return  # grid was rebuilt — abandon
                img = it.get("image")
                if not img:
                    continue
                try:
                    r = requests.get(url, params={
                        "dataset": dataset, "run_id": run_id,
                        "image": img, "size": 192,
                    }, timeout=15)
                    if r.ok:
                        self._thumb_done.emit(gen, idx, r.content)
                except Exception:
                    pass  # placeholder tile stays

        threading.Thread(target=work, daemon=True).start()

    def _on_thumb(self, gen, idx, data):
        if gen != self._thumb_gen or idx >= len(self._cells):
            return
        pix = QPixmap()
        if pix.loadFromData(data):
            self._cells[idx].set_thumbnail(pix)

    def _set_all_checks(self, checked):
        for cell in self._cells:
            cell.set_checked(checked)
        self._update_captions_header()

    def _check_all(self):
        self._set_all_checks(True)

    def _check_none(self):
        self._set_all_checks(False)

    def _checked_captions(self):
        return [c.caption for c in self._cells if c.is_checked()]

    def _update_captions_header(self):
        # Number the selected cards 1..N in grid order — exactly the line
        # each caption gets in the (re)deployed prompts txt, so a bad
        # prompt seen at line k is the card chipped "k".
        k = 0
        for cell in self._cells:
            if cell.is_checked():
                k += 1
                cell.set_order(k)
            else:
                cell.set_order(None)
        self.captions_header.setText(
            f"Captions — {k} of {len(self._cells)} selected")

    # -- deploy --------------------------------------------------------------

    def _deploy(self):
        if self._busy or not self._current_run:
            return
        ds_name, run = self._current_run
        ck = self.ckpt_combo.currentData()
        captions = self._checked_captions()
        slug = self.slug_edit.text().strip()
        if not ck:
            self.status_label.setText("Pick a checkpoint first")
            return
        if not captions:
            self.status_label.setText("Select at least one caption")
            return
        self._busy = True
        self.deploy_button.setEnabled(False)
        self.deploy_button.setText("Deploying…")
        self.status_label.setText(
            f"Deploying {ck} as '{slug}' with {len(captions)} prompt(s)…")
        self._post_async("lora_lab/deploy", {
            "dataset": ds_name,
            "run_id": run["run_id"],
            "checkpoint": ck,
            "captions": captions,
            "slug": slug,
        }, self._deploy_done)

    def _on_deploy_done(self, payload, error):
        self._busy = False
        self.deploy_button.setEnabled(self._current_run is not None)
        self.deploy_button.setText("Deploy LoRA")
        if error:
            self.status_label.setText(f"Deploy failed: {error}")
            return
        slug = payload.get("slug", "?")
        n = payload.get("n_prompts", "?")
        self.status_label.setText(
            f"Deployed '{slug}' ({payload.get('checkpoint', '?')}, "
            f"{n} prompts) — now selectable in the LoRA dropdown"
        )
        self._apply_registry(payload)

    # -- pair ----------------------------------------------------------------

    def _deployed(self):
        return (self._catalog or {}).get("deployed", {}) or {}

    def _populate_pair_combos(self):
        deployed = self._deployed()
        prev_a, prev_b = self.pair_a.currentText(), self.pair_b.currentText()
        for combo, prev in ((self.pair_a, prev_a), (self.pair_b, prev_b)):
            combo.blockSignals(True)
            combo.clear()
            for slug in sorted(deployed):
                np = deployed[slug].get("n_prompts", 0)
                combo.addItem(f"{slug}  ({np})", slug)
            idx = combo.findData(prev.split(" ")[0] if prev else "")
            if idx >= 0:
                combo.setCurrentIndex(idx)
            combo.blockSignals(False)
        self._validate_pair()

    def _pair_slugs(self):
        return self.pair_a.currentData(), self.pair_b.currentData()

    def _validate_pair(self):
        a, b = self._pair_slugs()
        deployed = self._deployed()
        ok, msg = False, ""
        if a and b:
            na = deployed.get(a, {}).get("n_prompts", 0)
            nb = deployed.get(b, {}).get("n_prompts", 0)
            if a == b:
                msg = "pick two distinct slugs"
            elif na == 0 or na != nb:
                msg = f"counts differ: {na} vs {nb}"
            else:
                ok, msg = True, f"{na} ↔ {nb} ✓"
        self.pair_info.setText(msg)
        self.pair_button.setEnabled(ok and not self._busy)

    def _create_pair(self):
        a, b = self._pair_slugs()
        if not (a and b) or self._busy:
            return
        self._busy = True
        self.pair_button.setEnabled(False)
        self.status_label.setText(f"Creating pair {a} + {b}…")
        self._post_async("lora_lab/pair", {"slug_a": a, "slug_b": b},
                         self._pair_done)

    def _on_pair_done(self, payload, error):
        self._busy = False
        self._validate_pair()
        if error:
            self.status_label.setText(f"Pair creation failed: {error}")
            return
        self.status_label.setText(
            f"Pair created: index {payload.get('index')} "
            f"({' + '.join(payload.get('loras', []))}) — in the idx quick-pick"
        )
        self._apply_registry(payload)

    # -- registry fan-out ----------------------------------------------------

    def _apply_registry(self, payload):
        """Push the response's fresh slug/preset lists to the main window
        and refresh our own catalog (deployed set changed)."""
        slugs = payload.get("slugs") or []
        presets = payload.get("presets") or {}
        if slugs:
            self.registry_updated.emit(list(slugs), dict(presets))
        self.refresh_catalog()
