"""LoRA Lab window — deploy trained kohya checkpoints as live LoRA slugs.

Flow (all server-side state, autogenerated — no git-tracked config):

  browse trained LoRAs (kohya datasets → runs, scanned server-side)
    → pick a checkpoint (step-ordered)
    → pick a caption subset (training captions, or the curated
      preview shortlist when one exists)
    → Deploy: the server copies the checkpoint into its deployed-LoRAs
      dir, writes the caption subset as the slug's prompt file, and
      refreshes its disk-derived slug registry.

The deploy/pair responses carry the updated slug + preset lists; the
window re-emits them as ``registry_updated`` so main.py can repopulate
the LoRA hot-swap dropdowns in place — the new LoRA is selectable in the
blending dropdown immediately, no reconnect / restart.

A second section pairs two deployed slugs into a curation-index preset
(requires equal prompt counts — paired prompt travel needs A[k]↔B[k]).

Server endpoints (web/server_realtime.py on sdxl-travel-ablation):
  GET  /api/installations/plantoid16/lora_lab          catalog + deployed
  POST /api/installations/plantoid16/lora_lab/deploy   {dataset, run_id,
                                                        checkpoint,
                                                        captions, slug}
  POST /api/installations/plantoid16/lora_lab/pair     {slug_a, slug_b}

HTTP runs in daemon worker threads; results come back via Qt signals
(queued to the GUI thread automatically).
"""

import re
import threading

import requests
from PySide6.QtCore import Qt, Signal
from PySide6.QtGui import QFont
from PySide6.QtWidgets import (QAbstractItemView, QComboBox, QGroupBox,
                               QHBoxLayout, QLabel, QLineEdit, QListWidget,
                               QListWidgetItem, QPushButton, QSplitter,
                               QTreeWidget, QTreeWidgetItem, QVBoxLayout,
                               QWidget)

_STEP_RE = re.compile(r"[-_](?:step)?0*(\d+)\.safetensors$")

_STYLE = """
QWidget { background: #11141b; color: #93a3bd; }
QGroupBox { border: 1px solid #1c2130; border-radius: 4px;
            margin-top: 10px; padding-top: 12px; }
QGroupBox::title { subcontrol-origin: margin; left: 8px; color: #7fd4ff; }
QTreeWidget, QListWidget { background: #0c0f15; border: 1px solid #1c2130; }
QLineEdit, QComboBox { background: #0c0f15; border: 1px solid #1c2130;
                       padding: 3px; }
QPushButton { background: #1c2130; border: 1px solid #2a3145;
              padding: 5px 12px; border-radius: 3px; }
QPushButton:hover { background: #2a3145; }
QPushButton:disabled { color: #4a5468; }
"""


def _slug_from_checkpoint(checkpoint: str) -> str:
    """Mirror of the server's suggestion: fire_XL-step00000700 → fire-xl."""
    stem = checkpoint
    if stem.endswith(".safetensors"):
        stem = _STEP_RE.sub("", stem)
        stem = stem[:-len(".safetensors")] if stem.endswith(".safetensors") else stem
    slug = stem.lower().replace("_", "-").strip("-")
    slug = re.sub(r"[^a-z0-9-]+", "-", slug)
    slug = re.sub(r"-{2,}", "-", slug).strip("-")
    return slug or "lora"


class LoraLabView(QWidget):
    """Deploy-pipeline window; see module docstring."""

    # (slugs, presets) — fresh registry after a deploy / pair-create.
    registry_updated = Signal(list, dict)

    # Internal: worker-thread → GUI-thread result delivery.
    _catalog_done = Signal(object, str)   # (payload | None, error)
    _deploy_done = Signal(object, str)
    _pair_done = Signal(object, str)

    def __init__(self, base_url_provider, parent=None):
        super().__init__(parent)
        self._base_url = base_url_provider
        self._catalog = None          # last GET /lora_lab payload
        self._current_run = None      # (dataset_name, run_dict)
        self._slug_edited = False     # user typed a custom slug
        self._busy = False

        self.setWindowTitle("LoRA Lab")
        self.resize(1000, 640)
        self.setStyleSheet(_STYLE)
        self._build_ui()

        self._catalog_done.connect(self._on_catalog_done)
        self._deploy_done.connect(self._on_deploy_done)
        self._pair_done.connect(self._on_pair_done)

    # -- UI ------------------------------------------------------------------

    def _build_ui(self):
        root = QVBoxLayout(self)

        top = QHBoxLayout()
        self.refresh_button = QPushButton("Refresh Catalog")
        self.refresh_button.clicked.connect(self.refresh_catalog)
        top.addWidget(self.refresh_button)
        self.status_label = QLabel("")
        self.status_label.setWordWrap(True)
        top.addWidget(self.status_label, 1)
        root.addLayout(top)

        split = QSplitter(Qt.Horizontal)
        root.addWidget(split, 1)

        # Left: trained LoRAs (datasets → runs).
        left = QWidget()
        ll = QVBoxLayout(left)
        ll.setContentsMargins(0, 0, 0, 0)
        ll.addWidget(QLabel("Trained LoRAs (kohya runs)"))
        self.tree = QTreeWidget()
        self.tree.setHeaderHidden(True)
        self.tree.itemSelectionChanged.connect(self._on_run_selected)
        ll.addWidget(self.tree, 1)
        split.addWidget(left)

        # Right: deploy panel + pair panel.
        right = QWidget()
        rl = QVBoxLayout(right)
        rl.setContentsMargins(0, 0, 0, 0)

        deploy_box = QGroupBox("Deploy checkpoint + captions as a live LoRA")
        dl = QVBoxLayout(deploy_box)

        row = QHBoxLayout()
        row.addWidget(QLabel("Checkpoint"))
        self.ckpt_combo = QComboBox()
        self.ckpt_combo.currentTextChanged.connect(self._on_ckpt_changed)
        row.addWidget(self.ckpt_combo, 1)
        dl.addLayout(row)

        row = QHBoxLayout()
        row.addWidget(QLabel("Slug"))
        self.slug_edit = QLineEdit()
        self.slug_edit.setPlaceholderText("e.g. fire-xl")
        self.slug_edit.textEdited.connect(self._on_slug_edited)
        row.addWidget(self.slug_edit, 1)
        dl.addLayout(row)

        self.trigger_label = QLabel("")
        f = QFont(); f.setItalic(True)
        self.trigger_label.setFont(f)
        dl.addWidget(self.trigger_label)

        cap_row = QHBoxLayout()
        self.captions_header = QLabel("Captions")
        cap_row.addWidget(self.captions_header, 1)
        self.src_combo = QComboBox()
        self.src_combo.addItem("training captions")
        self.src_combo.currentIndexChanged.connect(self._populate_captions)
        cap_row.addWidget(self.src_combo)
        for text, slot in (("All", self._check_all),
                           ("None", self._check_none)):
            b = QPushButton(text)
            b.setFixedWidth(52)
            b.clicked.connect(slot)
            cap_row.addWidget(b)
        dl.addLayout(cap_row)

        self.captions_list = QListWidget()
        self.captions_list.setSelectionMode(QAbstractItemView.NoSelection)
        self.captions_list.itemChanged.connect(
            lambda _i: self._update_captions_header())
        dl.addWidget(self.captions_list, 1)

        self.deploy_button = QPushButton("Deploy LoRA")
        self.deploy_button.clicked.connect(self._deploy)
        self.deploy_button.setEnabled(False)
        dl.addWidget(self.deploy_button)
        rl.addWidget(deploy_box, 1)

        pair_box = QGroupBox("Create pair (curation preset)")
        pl = QHBoxLayout(pair_box)
        self.pair_a = QComboBox()
        self.pair_b = QComboBox()
        self.pair_a.currentTextChanged.connect(self._validate_pair)
        self.pair_b.currentTextChanged.connect(self._validate_pair)
        pl.addWidget(QLabel("A"))
        pl.addWidget(self.pair_a, 1)
        pl.addWidget(QLabel("B"))
        pl.addWidget(self.pair_b, 1)
        self.pair_info = QLabel("")
        pl.addWidget(self.pair_info)
        self.pair_button = QPushButton("Create Pair")
        self.pair_button.clicked.connect(self._create_pair)
        self.pair_button.setEnabled(False)
        pl.addWidget(self.pair_button)
        rl.addWidget(pair_box)

        split.addWidget(right)
        split.setSizes([380, 620])

    # -- HTTP plumbing -------------------------------------------------------

    def _api(self, path: str) -> str:
        return f"{self._base_url()}/api/installations/plantoid16/{path}"

    def _get_async(self, path, done_signal):
        url = self._api(path)

        def work():
            try:
                r = requests.get(url, timeout=30)
                r.raise_for_status()
                done_signal.emit(r.json(), "")
            except Exception as e:
                done_signal.emit(None, str(e))

        threading.Thread(target=work, daemon=True).start()

    def _post_async(self, path, payload, done_signal):
        url = self._api(path)

        def work():
            try:
                r = requests.post(url, json=payload, timeout=120)
                if r.status_code >= 400:
                    # Surface FastAPI's {"detail": ...} instead of a bare
                    # status code.
                    try:
                        detail = r.json().get("detail", r.text)
                    except Exception:
                        detail = r.text
                    done_signal.emit(None, f"{r.status_code}: {detail}")
                    return
                done_signal.emit(r.json(), "")
            except Exception as e:
                done_signal.emit(None, str(e))

        threading.Thread(target=work, daemon=True).start()

    # -- catalog -------------------------------------------------------------

    def refresh_catalog(self):
        if self._busy:
            return
        self.status_label.setText("Loading catalog…")
        self.refresh_button.setEnabled(False)
        self._get_async("lora_lab", self._catalog_done)

    def _on_catalog_done(self, payload, error):
        self.refresh_button.setEnabled(True)
        if error:
            self.status_label.setText(f"Catalog fetch failed: {error}")
            return
        self._catalog = payload
        cat = payload.get("catalog", {})
        n_ds = len(cat.get("datasets", []))
        n_deployed = len(payload.get("deployed", {}))
        self.status_label.setText(
            f"{n_ds} trained dataset(s) under {cat.get('kohya_root', '?')} · "
            f"{n_deployed} deployed slug(s)"
        )
        self._populate_tree()
        self._populate_pair_combos()

    def _populate_tree(self):
        self.tree.clear()
        cat = (self._catalog or {}).get("catalog", {})
        for ds in cat.get("datasets", []):
            top = QTreeWidgetItem([ds["name"]])
            top.setFlags(top.flags() & ~Qt.ItemIsSelectable)
            for run in ds.get("runs", []):
                n_ck = len(run.get("checkpoints", []))
                n_cap = len(run.get("captions", []))
                label = f"{run['run_id']} · {n_ck} ckpt · {n_cap} captions"
                if run.get("shortlist"):
                    label += f" · shortlist({len(run['shortlist'])})"
                child = QTreeWidgetItem([label])
                child.setData(0, Qt.UserRole, (ds["name"], run))
                top.addChild(child)
            self.tree.addTopLevelItem(top)
        self.tree.expandAll()

    # -- run / checkpoint / captions selection -------------------------------

    def _on_run_selected(self):
        items = self.tree.selectedItems()
        data = items[0].data(0, Qt.UserRole) if items else None
        if not data:
            return
        ds_name, run = data
        self._current_run = (ds_name, run)
        self._slug_edited = False

        self.ckpt_combo.blockSignals(True)
        self.ckpt_combo.clear()
        for ck in run.get("checkpoints", []):
            step = ck.get("step")
            label = ck["file"] if step is None else f"{ck['file']}  (step {step})"
            self.ckpt_combo.addItem(label, ck["file"])
        # Default to the LAST (highest-step) checkpoint.
        if self.ckpt_combo.count():
            self.ckpt_combo.setCurrentIndex(self.ckpt_combo.count() - 1)
        self.ckpt_combo.blockSignals(False)

        trig = run.get("trigger")
        self.trigger_label.setText(f"trigger: {trig}" if trig else "")

        self.src_combo.blockSignals(True)
        self.src_combo.clear()
        self.src_combo.addItem("training captions")
        if run.get("shortlist"):
            self.src_combo.addItem("curated shortlist")
        self.src_combo.blockSignals(False)

        self._suggest_slug()
        self._populate_captions()
        self.deploy_button.setEnabled(True)

    def _on_ckpt_changed(self, _text):
        self._suggest_slug()

    def _on_slug_edited(self, _text):
        self._slug_edited = True

    def _suggest_slug(self):
        if self._slug_edited:
            return
        ck = self.ckpt_combo.currentData()
        if ck:
            self.slug_edit.setText(_slug_from_checkpoint(ck))

    def _caption_pool(self):
        if not self._current_run:
            return []
        _ds, run = self._current_run
        if self.src_combo.currentText() == "curated shortlist":
            return run.get("shortlist") or []
        return run.get("captions") or []

    def _populate_captions(self):
        self.captions_list.blockSignals(True)
        self.captions_list.clear()
        for cap in self._caption_pool():
            item = QListWidgetItem(cap)
            item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
            item.setCheckState(Qt.Checked)
            self.captions_list.addItem(item)
        self.captions_list.blockSignals(False)
        self._update_captions_header()

    def _set_all_checks(self, state):
        self.captions_list.blockSignals(True)
        for i in range(self.captions_list.count()):
            self.captions_list.item(i).setCheckState(state)
        self.captions_list.blockSignals(False)
        self._update_captions_header()

    def _check_all(self):
        self._set_all_checks(Qt.Checked)

    def _check_none(self):
        self._set_all_checks(Qt.Unchecked)

    def _checked_captions(self):
        out = []
        for i in range(self.captions_list.count()):
            item = self.captions_list.item(i)
            if item.checkState() == Qt.Checked:
                out.append(item.text())
        return out

    def _update_captions_header(self):
        n = len(self._checked_captions())
        total = self.captions_list.count()
        self.captions_header.setText(f"Captions — {n} of {total} selected")

    # -- deploy --------------------------------------------------------------

    def _deploy(self):
        if self._busy or not self._current_run:
            return
        ds_name, run = self._current_run
        ck = self.ckpt_combo.currentData()
        captions = self._checked_captions()
        slug = self.slug_edit.text().strip()
        if not ck:
            self.status_label.setText("Pick a checkpoint first")
            return
        if not captions:
            self.status_label.setText("Select at least one caption")
            return
        self._busy = True
        self.deploy_button.setEnabled(False)
        self.deploy_button.setText("Deploying…")
        self.status_label.setText(
            f"Deploying {ck} as '{slug}' with {len(captions)} prompt(s)…")
        self._post_async("lora_lab/deploy", {
            "dataset": ds_name,
            "run_id": run["run_id"],
            "checkpoint": ck,
            "captions": captions,
            "slug": slug,
        }, self._deploy_done)

    def _on_deploy_done(self, payload, error):
        self._busy = False
        self.deploy_button.setEnabled(self._current_run is not None)
        self.deploy_button.setText("Deploy LoRA")
        if error:
            self.status_label.setText(f"Deploy failed: {error}")
            return
        slug = payload.get("slug", "?")
        n = payload.get("n_prompts", "?")
        self.status_label.setText(
            f"Deployed '{slug}' ({payload.get('checkpoint', '?')}, "
            f"{n} prompts) — now selectable in the LoRA dropdown"
        )
        self._apply_registry(payload)

    # -- pair ----------------------------------------------------------------

    def _deployed(self):
        return (self._catalog or {}).get("deployed", {}) or {}

    def _populate_pair_combos(self):
        deployed = self._deployed()
        prev_a, prev_b = self.pair_a.currentText(), self.pair_b.currentText()
        for combo, prev in ((self.pair_a, prev_a), (self.pair_b, prev_b)):
            combo.blockSignals(True)
            combo.clear()
            for slug in sorted(deployed):
                np = deployed[slug].get("n_prompts", 0)
                combo.addItem(f"{slug}  ({np})", slug)
            idx = combo.findData(prev.split(" ")[0] if prev else "")
            if idx >= 0:
                combo.setCurrentIndex(idx)
            combo.blockSignals(False)
        self._validate_pair()

    def _pair_slugs(self):
        return self.pair_a.currentData(), self.pair_b.currentData()

    def _validate_pair(self):
        a, b = self._pair_slugs()
        deployed = self._deployed()
        ok, msg = False, ""
        if a and b:
            na = deployed.get(a, {}).get("n_prompts", 0)
            nb = deployed.get(b, {}).get("n_prompts", 0)
            if a == b:
                msg = "pick two distinct slugs"
            elif na == 0 or na != nb:
                msg = f"counts differ: {na} vs {nb}"
            else:
                ok, msg = True, f"{na} ↔ {nb} ✓"
        self.pair_info.setText(msg)
        self.pair_button.setEnabled(ok and not self._busy)

    def _create_pair(self):
        a, b = self._pair_slugs()
        if not (a and b) or self._busy:
            return
        self._busy = True
        self.pair_button.setEnabled(False)
        self.status_label.setText(f"Creating pair {a} + {b}…")
        self._post_async("lora_lab/pair", {"slug_a": a, "slug_b": b},
                         self._pair_done)

    def _on_pair_done(self, payload, error):
        self._busy = False
        self._validate_pair()
        if error:
            self.status_label.setText(f"Pair creation failed: {error}")
            return
        self.status_label.setText(
            f"Pair created: index {payload.get('index')} "
            f"({' + '.join(payload.get('loras', []))}) — in the idx quick-pick"
        )
        self._apply_registry(payload)

    # -- registry fan-out ----------------------------------------------------

    def _apply_registry(self, payload):
        """Push the response's fresh slug/preset lists to the main window
        and refresh our own catalog (deployed set changed)."""
        slugs = payload.get("slugs") or []
        presets = payload.get("presets") or {}
        if slugs:
            self.registry_updated.emit(list(slugs), dict(presets))
        self.refresh_catalog()
